/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsTeamAccessRouteImport } from './routes/settings/team-access'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamAccessRoute = SettingsTeamAccessRouteImport.update({
  id: '/settings/team-access',
  path: '/settings/team-access',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/categories': typeof CategoriesRoute
  '/growth': typeof GrowthRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/services': typeof ServicesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/users': typeof UsersRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/team-access': typeof SettingsTeamAccessRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/categories': typeof CategoriesRoute
  '/growth': typeof GrowthRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/services': typeof ServicesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/users': typeof UsersRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/team-access': typeof SettingsTeamAccessRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/businesses': typeof BusinessesRoute
  '/categories': typeof CategoriesRoute
  '/growth': typeof GrowthRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/requests': typeof RequestsRoute
  '/services': typeof ServicesRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/users': typeof UsersRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/team-access': typeof SettingsTeamAccessRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/businesses'
    | '/categories'
    | '/growth'
    | '/login'
    | '/notifications'
    | '/products'
    | '/reports'
    | '/requests'
    | '/services'
    | '/subscriptions'
    | '/users'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/team-access'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/businesses'
    | '/categories'
    | '/growth'
    | '/login'
    | '/notifications'
    | '/products'
    | '/reports'
    | '/requests'
    | '/services'
    | '/subscriptions'
    | '/users'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/team-access'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/businesses'
    | '/categories'
    | '/growth'
    | '/login'
    | '/notifications'
    | '/products'
    | '/reports'
    | '/requests'
    | '/services'
    | '/subscriptions'
    | '/users'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/team-access'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessesRoute: typeof BusinessesRoute
  CategoriesRoute: typeof CategoriesRoute
  GrowthRoute: typeof GrowthRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  RequestsRoute: typeof RequestsRoute
  ServicesRoute: typeof ServicesRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  UsersRoute: typeof UsersRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsTeamAccessRoute: typeof SettingsTeamAccessRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team-access': {
      id: '/settings/team-access'
      path: '/settings/team-access'
      fullPath: '/settings/team-access'
      preLoaderRoute: typeof SettingsTeamAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessesRoute: BusinessesRoute,
  CategoriesRoute: CategoriesRoute,
  GrowthRoute: GrowthRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  RequestsRoute: RequestsRoute,
  ServicesRoute: ServicesRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  UsersRoute: UsersRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsTeamAccessRoute: SettingsTeamAccessRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
